// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jeiwmghpozanqqqixjrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplaXdtZ2hwb3phbnFxcWl4anJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2Mzc3ODMsImV4cCI6MjA2MzIxMzc4M30.t5IVGUGIZxnYgtH94CuwKv3Ju0iZti90aQbUo2q8Hk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);